{
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
        "ID": "CVE-2021-32613",
        "ASSIGNER": "patrick@puiterwijk.org",
        "STATE": "PUBLIC"
    },
    "affects": {
        "vendor": {
            "vendor_data": [
                {
                    "vendor_name": "n/a",
                    "product": {
                        "product_data": [
                            {
                                "product_name": "radare2",
                                "version": {
                                    "version_data": [
                                        {
                                            "version_value": "radare2 versions before and including 5.3.0"
                                        }
                                    ]
                                }
                            }
                        ]
                    }
                }
            ]
        }
    },
    "problemtype": {
        "problemtype_data": [
            {
                "description": [
                    {
                        "lang": "eng",
                        "value": "CWE-416"
                    }
                ]
            }
        ]
    },
    "references": {
        "reference_data": [
            {
                "refsource": "MISC",
                "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1959939",
                "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1959939"
            },
            {
                "refsource": "MISC",
                "name": "https://github.com/radareorg/radare2/issues/18679",
                "url": "https://github.com/radareorg/radare2/issues/18679"
            }
        ]
    },
    "description": {
        "description_data": [
            {
                "lang": "eng",
                "value": "In radare2 through 5.3.0 there is a double free vulnerability in the pyc parse via a crafted file which can lead to DoS."
            }
        ]
    }
}